#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "trigger-v2-fly-demo"
primary_region = "mia"

[build]
  image = "ghcr.io/triggerdotdev/trigger.dev:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
